### ISSUE TITLE
Request: provide optional paths to config file.

### ISSUE THREAD

**Issue by jorana** [XENONnT/utilix#6]
I wonder if we could also provide optional paths (tuple of optional paths) to the place we are trying to find the config.ini:
https://github.com/XENONnT/utilix/blob/master/utilix/config.py#L29

This might make it easier for users to init utilix if they can just provide an abspath to the ini file

**Comment by ershockley** [comment]
Thanks @jorana. We can consider this, but there are a few issues at the moment.

The config class is a [singleton](https://github.com/XENONnT/utilix/blob/master/utilix/config.py#L21), so that there are not multiple instances running around (which is a good thing usually). I quickly implemented your suggestion to show you an example:

```
>>> import utilix
2020-11-10 13:38:58,789 - utilix - WARNING - $XENON_CONFIG is not defined in the environment
>>> c1 = utilix.config.Config()
>>> c1.config_path
'/home/ershockley/.xenon_config'
>>>
>>> c2 = utilix.config.Config(path='path/to/nowhere')
>>> c2.config_path
'/home/ershockley/.xenon_config'
```
You can see the path stays the same -- this is because the config gets instantiated during the utilix `__init__`. 

So if this is important, we could modify utilix to not instantiate the config (and the rundb class) on startup. This makes things slightly more annoying from a user perspective, IMO. Again to be explicit:

(currently)
```
from utilix import db
# now can immediately call DB methods
```

vs 
```
from utilix.rundb import DB
db = DB()
# now can do DB methods
```

Personally I feel like the environment variable setup should be flexible enough. What do you think?

**Comment by jorana** [comment]
Interesting, I see. Thanks for looking into it, I thought it'd be easier. I'll close this issue then.

Perhaps I will need your help trying to get the config file in the bleeding edge environment. Let me see how far I get.
